### ISSUE TITLE
Features to deliver based on meeting with Jane

### ISSUE THREAD

**Issue by krico** [krico/jas#182]
When we met with Jane last time we agreed on features that would be available.  I will centralize them in this issue.

## Subscriber

 * List Activities with button to subscribe/add to basket
 * List Promotions with button to subscribe
 * Checkout/Pay (#143, #228, #205)

## Publisher

 * [Create Promotion](https://github.com/krico/jas/issues/232)
 * [View Subscriptions](https://github.com/krico/jas/issues/188)
 * View Balance (#228 closed this)

As I create issues I will edit this issue and link them.  How di this link to the other one?

**Comment by wszarmach** [comment]
For Publisher view subscriptions, is that view subscriptions for an activity or also something else?

**Comment by krico** [comment]
I think for an activity is what makes sense

**Comment by krico** [comment]
How do I make this issue link to the other one?

**Comment by pauljanes** [comment]
From meeting from the 17th April Jayne gave following feedback:

In general she thought what we had so far was pretty good but there were a few things she mentioned to change/ add

1) The repeat weekly functionality - she said was not so clear what Every meant and would be better to have labels to explain it. Also the selection of the days - she said that instead of using light blue and dark blue to show whether selected or not, we should use different colours. Because she said its not easy to see the difference in shades to know what is selected and what is not.
2) She needs option to switch off pay at door functionality for her org - she said she wants that everyone who turns up she knows must have already paid
3) The point above means that for her go live you need to release the reserved place after a certain time limit eg 10 minutes if the paypal transaction was not successfully completed. You should display a message to user like "You have 10 minutes to complete this transaction before the reservation will be released" and then a countdown timer. Also you need to make sure not to send out subscription emails until the payment is successful. She noticed this without me even pointing it out, that she had an email in her inbox even though I had not completed the paypal payment.
4) She is fine with making the user select the 12 classes upfront if they want her 12 class package (I explained how you intend to implement it). The only thing she said is that she would want a function as org admin that she can instead of cancelling a subscription, that she can move it to another class. As basically the person has already paid, so it shouldnt be too complicated. Its just that she wants everything in the system, and not some things in the system and then a separate list of people who had called her and asked her to shift class. Cancelling a subscription and then they can enter a new one makes sense if the person has not paid, but in Jaynes case as she will deselect the pay at door option, everyone who has subscribed has paid. So move subscription rather than the cancel subscription is the correct behaviour in this case. For now it can be an org admin function only. No need to allow users to shift classes for now.
5) When we created her classes for the coming term, when we saw the list of activities, they were not showing in date order and this caused us a lot of confusion. The activities list needs to be date sorted.
6) In the subscription mail she says we should show the payment option applied. In her case she will disable pay at door, but she said you should know whether it was pay at door or paid with paypal.
7) In the list of subscriptions for a class, she said she would like to see payment type as well as the name and the email of the user. So basically the same as the subscription mail, but in the subscription list.
8) She needs to be able to select a time for the class start and class end. At the moment you select a date in the date picker and then it automatically populates time in the text field. Then you have to go into the text field and edit it. She wants a separate field where you can select the time from a dropdown menu. This makes it easier to enter on the mobile for instance.
9) There was also the issue where the labels like Create were not fully on the page and show as reate. Separate issue was already raised for that with screenshot.
10) She also noticed the fact that if you enter the password wrong once then the Sign In button is disabled. I know there is already a separate issue in the system for that.
11) And she mentioned that on the forgot password logic it was confusing because the forgot password screen does not disappear once you have reset it successfully.
12) For go live she wants an iframe or something that can be embedded in her site where the user can see all the things they can buy - like the single classes as well as the packages and that they can add them all into the basket and then checkout once they are done with a single transaction

For go live she is ok like we have done it now where she sets the prices and then we charge the handling fee on top, but she said perhaps it would be better if she raises her prices to cover the paypal charges so that the user will pay exactly the price they see listed on her site and not that price plus a handling fee. I also explained to her that the handling fee is a guess based on the "normal" transaction fee. We can leave it like this for now but she said we should perhaps revisit this later to give the user more transparency.

To go live on June she wants 3 weeks of testing. So May 10th should be considered as a HARD deadline for having the bundle functionality and taking care of the above fixes/ enhancements. After May 10th there should only be minor bug fixes, but all the functionality needs to be there by then.

Later on she would like a wait list functionality but this is not needed for go live on 1st June. 

She liked the idea of being able to pay with jasify credits as then someone could do a bank transfer to our account and we could credit them with jasify credits if they didnt have a credit card or paypal for instance. That would just be an admin function to award someone with credits because I could check the bank account and when I see someone has made a transfer to us, I could award them credits. Of course they can also buy credits using paypal and that is handled automatically. Credits is not required for 1st June go live.

After go live she wants us to work on a set up so that the money goes directly to her account. Basically  most providers will expect the money to go straight to their account minus our booking fee. Wally mentioned that we have the possibility to chain paypal payments - we should look at implementing this as soon as we have all Jaynes classes on our platform. because once we have several providers it will be hard to keep track of how much we need to send from our paypal account to each providers paypal account. The process needs to be automated. For Jayne go live its easy as all the money in the paypal account is for Jayne. But it isnt scaleable till we do chaining or something like this.

**Comment by wszarmach** [comment]
For item 1 button colour see #296

**Comment by wszarmach** [comment]
I will close this as the only remaining issue is not a high priority
