### ISSUE TITLE
Remove/Disable ActivityType and Organization

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#237]
The current logic allows a publisher or admin to remove an ActivityType only if no activities exist with that type.

It might be that at some point a publisher decides to stop offering a specific ActivityType and no longer wants to see it in the list of possible ActivityTypes or an Organization stops using Jasify. In these cases should we have a disable option?

**Comment by pauljanes** [comment]
Is this the behavior in prod that you are describing? Because the other day I managed to screw myself because I couldnt edit the activitytype description as there is no edit option. So I deleted the activitytype even though it had associated activities. Then it was screwed because for that org I couldnt see any of the other activitytypes. I guess exceptions were being thrown on backend because of hanging references of activities to a deleted activitytype. In the end I had to create a completely new org

**Comment by wszarmach** [comment]
The PR is pending but once done its the behaviour.

**Comment by wszarmach** [comment]
We can look into this issue when the situation requires it
