### ISSUE TITLE
Activity list must be sorted by start date

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#297]
From #182 item 5
> When we created her classes for the coming term, when we saw the list of activities, they were not showing in date order and this caused us a lot of confusion. The activities list needs to be date sorted.

**Comment by pauljanes** [comment]
I just created some classes in prod and they are still not date sorted when I view the activities. See attached screenshot.
![screen shot 2015-05-13 at 13 42 21](https://cloud.githubusercontent.com/assets/9402268/7609725/60f1f6b0-f976-11e4-941a-67f0a49db59e.png)

**Comment by pauljanes** [comment]
After browser refresh it is then sorted correctly. The above activities were created using the Repeat functionality, so I guess this doesnt go through the sorting code like it should.

**Comment by pauljanes** [comment]
Wally says this is browser caching issue. So I will close this as since refreshing and trying it out again the problem doesnt occur. But we cant rely on our clients/ users to refresh their browsers when we release a new version of jasify so we need to think of a solution for this in order to force a browser refresh.

**Comment by dragonflypl** [comment]
We will implementacji cache busting.

Should i make i prio for next release?
13 maj 2015 14:09 "pauljanes" <notifications@github.com> napisał(a):

**Comment by pauljanes** [comment]
Would be good yes. Else we cant be confident when releasing bug fixes that client will get fix
