### ISSUE TITLE
Activity Package with invalid item count

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#313]
During my testing of activity packages I found the following bugs;
* I could create an activity package with item count = 0
* I could create an activity package with item count = 5 but only containing less than 5 activities

To be safe both front end and backend should catch these

**Comment by dragonflypl** [comment]
Regarding second point, i think I don't understand how Item Count works. Tooltip says: "A number of activities a client can subscribe to"

**Comment by pauljanes** [comment]
There might be eg 24 activities in the package.

If item count is 10, it means client can do 10 of the 24 possible activities. They must then choose which one. If avtivity package contains 24 activities and item count is 24 then the client should automatically be subscribed to all.

Item count is probably not the best name. In fact it is more like "max items"

**Comment by wszarmach** [comment]
I think a fix to fronted is required and for completeness a fix to backend to catch these situations. I will do the backend

**Comment by dragonflypl** [comment]
Thanks,

- "Max items" means that you can select "0 < item count <= max items". But Waldemars bug suggets item count == max items. Correct? If so, then you do you need this field ? It could be replaced with "Add All Activities To Package" button.

**Comment by pauljanes** [comment]
It is not always the case that you can do the max nbr of possible activities though. Packages usually offer a better price than signing up for individual activities. Eg you can do 12 classes in a package for the price of 10 individual classes.

Example 1: 24 activities in bootcamp package - client has to choose 12 of them

Example 2: 24 activities in bootcamp package - client has to choose 24 of them (so here automation makes sense)

In examples 1 and 2 it makes no sense for client to choose less than the max that they are allowed to choose, because they have paid for it when they buy the package. Eg in example 1 above, if client only chooses 11 of the possible 12 they are allowed to choose, then they are not getting the full value of the package. If they only select 11 in example 1 above I think there should be a warning like "You are permitted to choose 12 activities, but you have only chosen 11. Are you sure?"

**Comment by wszarmach** [comment]
Max items suggests that you can select up to this many items. This is not correct. Item count is the exact number of activities the publisher should select. The bug is that the publisher set item count to X but added < X activities to the list. In other words we allow the subscriber to choose 5 activities but only have 3 activities to choose from.
Having said all that what should happen if some of the choices are no longer valid because their start time is now in the past?

**Comment by pauljanes** [comment]
Discussed with Waldemar. I dont think we should baby the subscribers. If some activities have already passed then he just signs up for what he wants but he can still buy package.

In jaynes case if one activity is passed, the 12 class package is still cheaper than buying 11 classes individually. 

When you buy on Amazon, amazon does not make sure you dont buy a more expensive option. They give you the choice of same book at different prices and you get to decide

**Comment by pauljanes** [comment]
This is not correct by the way in Waldemar's comment:

> Max items suggests that you can select up to this many items. This is not correct. Item count is the exact number of activities the publisher should select. 
> 

Actually the publisher eg Jayne can add more activities than item count. She must add AT LEAST item count nbr of activities, but it can be more. So the word "exact" in his comment is wrong. 

Item count represents the number of activities from all the possible activities that the subscriber has the right to sign up to.

**Comment by dragonflypl** [comment]
This one is already fixed, at least on frontend. Reassigning to Chris
