### ISSUE TITLE
Creating new Activity Package should not show Activities in the past

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#322]
I started to make a new Activity Package and noticed that some of the possible Activities to add were in the past. These should not be visible. Ideally the front end should only query for Activities with Start Time greater then current time.

**Comment by pauljanes** [comment]
Jayne also thought that activities in the past should not be visible when creating an activity package. As well as not allowing users to book activities in the past. She was of the opinion that only org admin or admin would have a reason to add users to an activity where the date has already passed eg if a user turned up at the door and she wanted to add the user so that she had a complete list of who attended the class.
