### ISSUE TITLE
Give providers like Jayne the ability to define colours for each Activity type

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#425]
In the tables it would be much easier for both providers and subscribers to find what they are looking for, if the different activities were shown in different colours according to the activity type.

When the provider creates or edits an activity type, we could give them the ability to define the colour using the hex colour codes eg #ff4444, Activities created with this activity type would then be shown in tables using this colour background.

Jayne has asked for this. I tend to agree with her that users need a way to quickly find what they are looking for. So for instance once they realise that Metafit is red, next time they can quickly find the Metafit.

**Comment by dragonflypl** [comment]
What do you think about this:
- no background color. I tried with solid background, gradients etc, they all looked to agressive imho :)  And there was too much color on the page
- instead:
 - activity name with background
 - gentle left/bottom border

Also I slightly moved info boxes so that the same information is always visible in the same area of the page (price/places left on the right, location & date below activity name)

![image](https://cloud.githubusercontent.com/assets/5444220/7802310/3b2ac648-0333-11e5-8ed3-18629e6890dd.png)

**Comment by pauljanes** [comment]
I like it like you have it in the screenshot. And its much easier to find what you are looking for
