### ISSUE TITLE
Chris to phone the MWST (VAT) people and clarify when we would need to pay MWST

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#456]
Whether we have to pay VAT based off money received in our account or based on profit will have a big impact on our payment model. Currently Jayne for instance is just under the VAT limit. If we have 2 providers and collect the money in our account (even if only temporarily) and we are expected to pay VAT on the total that passes through our account then we would need to change our payment model. Clarifying with the MWST and ideally getting it in writing will put us on safer ground.

Eidgenössische Steuerverwaltung ESTV (Zurich nord) 058 465 78 54

**Comment by pauljanes** [comment]
I just spoke to a Swiss friend and she thinks that it should not count as our turnover if the money is just flowing THROUGH our account. She said you should explain this on the phone. That what comes in goes out and our paypal is just a temporary step in the middle. But it would be good to have it in writing though in an email for example and to have someone also confirm on phone.

**Comment by krico** [comment]
I called the MWST office and the person I spoke to basically said what we already new:

> If your turnover is above CHF 100k you are Mehrwertsteuerpflichtig

Then I explained the case to him with a short example:

 * client buys a product for CHF 101K from our website
 * he deposits CHF 101K in our account
 * we transfer 100k to our supplier and keep 1k
 * we do no other sale for the rest of the year

And asked "Are we required to declare VAT?"

His answer:

> What is your "taxable" turnover in your example?

It turns out we need an accountant to tell us what is our *taxable turnover* is, the MWST guy probably knows, but if he officially states it he is liable later, so he won't do it.

I hired an accountant for a quick consultancy, gave him a different example:

 * We sell 40 classes a day every day of the week (9600 classes) for CHF 20.- each (CHF 192'000.-/year)
 * We charge CHF 1.- for every sold class  (CHF 9'600.- /year)

And asked him "what is my turnover", he said:

> If your turnover in services is less than CHF 100K, you are exempt from VAT
> I don’t see any problem with this business idea.
> It is not quite clear. I would say your 10k service charge is the turnover as it is similar to credit cards.

So, really, unless we hire an accountant we will not get a "commitment" in terms of what is our turnover.  We should continue as if this were the case (turnover = "service fees").

In any case, one important information I got from MWST guy is **You cannot even mention MWST in you bills unless you have a MWST number, that would be a crime**

**Comment by pauljanes** [comment]
Ok thanks Chris. So basically I think we go ahead till we earn 100k in service fees. Which also matches with what my Swiss friend told me.

The only drawback we will have is if paypal stops us from using the free transfer to friends and family option. I used it yesterday to transfer 35 chf to jayne and it worked. But they might stop it at some point if we are using it for regular payments. Then we would need to consider how to get the money to the providers.

I am now registered as selbstandig officially, with an einzelfirma called MyWayFit so its official now from my end. And I have to pay AHV etc. As its an Einzelfirma currently there is no mention of you guys. We need a gmbh if you want to define things properly. But then we also need to submit accounts, pay for incorporation plus insurance.
