### ISSUE TITLE
On iphone 5 the screens dont look so great

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#476]
I was looking at jasify on my iphone and it still doesnt look that great. When I sign in with my own account the initial screen is ok. But look what happens when I sign in with Jayne's account which has a longer email. This is the first view that she gets.

![image 1](https://cloud.githubusercontent.com/assets/9402268/7900832/36717932-076e-11e5-8cad-4748dce3940a.png)

Once I am on Jaynes welcome screen like above I click on Organizations but nothing seems to happen. Then I click activities and I see the activities. Then I click Organizations and now finally I get to see the organizations screen. What is the difference about the first time I clicked on Organizations and it didnt work and the second time after going first to Activities and then Organizations that it now works? 

Now that I finally manage to see the Organizations screen (after having to go first to Activities then back to Organizations), it doesnt display properly on the page. As you can see in the screenshot it goes off the right hand side of the screen.

![image 2](https://cloud.githubusercontent.com/assets/9402268/7900833/36720e38-076e-11e5-9705-8878064a648e.png)

**Comment by dragonflypl** [comment]
a) for main page: do you have any suggestions how it should look like (instead of email). My idea it so give the user a few block buttons with most common actions (add org, activity, activity type etc), typical dashboard
b) as for organizations not loaded properly - i've already added delicate progressbar indicator. I will show when something is happening. Perhaps when you log in and try to access organizations, server needs some time to start working with you session (maybe some caching etc, i don't to server so i don't  know). With progress bar user will see that content is loading & patiently wait for finish. 
c) as for tables not rendering properly, this is my task for upcoming days (along with translation). I'll prepare one-two pages for quick feedback

**Comment by dragonflypl** [comment]
@pauljanes : Also question: usually on small devices less information is displayed for tabular data. Which columns should be displayed on iphone for activities list?

**Comment by pauljanes** [comment]
Activity name, start date and time, end date and time and number of subscriptions eg 1 of 6 would be the most important fields. 

The provider knows their own location, price, description etc. They just need things that will quickly help them distinguish between the activities and to see how many people have subscribed.

**Comment by pauljanes** [comment]
a) i like the idea of message saying "Welcome Paul" for example, plus the main buttons as you suggested
b) chris should look at this then as its not just slow. First I get the popup in the screenshot below and then when I select Not Now, nothing happens even if I wait for several minutes. The only way I can get menu to go away is by clicking something else other than Organizations and then by going to Organizations eg Activities then Organizations

**Comment by dragonflypl** [comment]
I worked on Organizations + Activities pages. Rest will do after resolving #487 (Focus for the coming days). Please let me know what you think

**Comment by pauljanes** [comment]
Sounds good to me if its ok with Waldemar. Essentially 487 is all that is preventing us from handling all the flow of No Excuses Zurich. If we can go live with one fitness provider in July then everything can grow fron there.

**Comment by dragonflypl** [comment]
I also ment what do you think about new look od tables after release :)
